/**
 * Pokemon Card Pack Simulator - Card Data
 * Generated: 2026-02-22T12:52:26.212Z
 * Images: images.pokemontcg.io CDN (no API key needed)
 */

const PACK_DATA = {
  'sv8': {
    info: {
      id: 'sv8',
      name: 'Surging Sparks',
      nameKo: '초전브레이커',
      fullName: 'Scarlet & Violet — Surging Sparks',
      totalCards: 252,
      baseCards: 191,
      releaseDate: '2024-11-08',
      cardsPerPack: 10,
      price: 1500,
      packImage: 'assets/sv8_pack_kr.png',
      maxImageId: 252,
      coverColor: 'linear-gradient(135deg, #ff6b00, #ffcc00)'
    },
    cards: [
      { id: 1, name: "Exeggcute", type: 'grass', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/1.png', imageLarge: 'https://images.pokemontcg.io/sv8/1_hires.png' },
      { id: 2, name: "Exeggcute", type: 'grass', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/2.png', imageLarge: 'https://images.pokemontcg.io/sv8/2_hires.png' },
      { id: 3, name: "Exeggutor", type: 'grass', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/3.png', imageLarge: 'https://images.pokemontcg.io/sv8/3_hires.png' },
      { id: 4, name: "Durant ex", type: 'steel', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/4.png', imageLarge: 'https://images.pokemontcg.io/sv8/4_hires.png' },
      { id: 5, name: "Scatterbug", type: 'grass', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/5.png', imageLarge: 'https://images.pokemontcg.io/sv8/5_hires.png' },
      { id: 6, name: "Spewpa", type: 'grass', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/6.png', imageLarge: 'https://images.pokemontcg.io/sv8/6_hires.png' },
      { id: 7, name: "Vivillon", type: 'grass', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/7.png', imageLarge: 'https://images.pokemontcg.io/sv8/7_hires.png' },
      { id: 8, name: "Morelull", type: 'grass', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/8.png', imageLarge: 'https://images.pokemontcg.io/sv8/8_hires.png' },
      { id: 9, name: "Shiinotic", type: 'grass', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/9.png', imageLarge: 'https://images.pokemontcg.io/sv8/9_hires.png' },
      { id: 10, name: "Dhelmise", type: 'grass', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/10.png', imageLarge: 'https://images.pokemontcg.io/sv8/10_hires.png' },
      { id: 11, name: "Zarude", type: 'grass', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/11.png', imageLarge: 'https://images.pokemontcg.io/sv8/11_hires.png' },
      { id: 12, name: "Capsakid", type: 'fire', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/12.png', imageLarge: 'https://images.pokemontcg.io/sv8/12_hires.png' },
      { id: 13, name: "Rellor", type: 'fighting', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/13.png', imageLarge: 'https://images.pokemontcg.io/sv8/13_hires.png' },
      { id: 14, name: "Rabsca", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/14.png', imageLarge: 'https://images.pokemontcg.io/sv8/14_hires.png' },
      { id: 15, name: "Wo-Chien", type: 'grass', rarity: 'R', imageSmall: 'https://images.pokemontcg.io/sv8/15.png', imageLarge: 'https://images.pokemontcg.io/sv8/15_hires.png' },
      { id: 16, name: "Vulpix", type: 'fire', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/16.png', imageLarge: 'https://images.pokemontcg.io/sv8/16_hires.png' },
      { id: 17, name: "Ninetales", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/17.png', imageLarge: 'https://images.pokemontcg.io/sv8/17_hires.png' },
      { id: 18, name: "Paldean Tauros", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/18.png', imageLarge: 'https://images.pokemontcg.io/sv8/18_hires.png' },
      { id: 19, name: "Ho-Oh", type: 'fire', rarity: 'R', imageSmall: 'https://images.pokemontcg.io/sv8/19.png', imageLarge: 'https://images.pokemontcg.io/sv8/19_hires.png' },
      { id: 20, name: "Castform Sunny Form", type: 'fire', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/20.png', imageLarge: 'https://images.pokemontcg.io/sv8/20_hires.png' },
      { id: 21, name: "Victini", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/21.png', imageLarge: 'https://images.pokemontcg.io/sv8/21_hires.png' },
      { id: 22, name: "Pansear", type: 'fire', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/22.png', imageLarge: 'https://images.pokemontcg.io/sv8/22_hires.png' },
      { id: 23, name: "Simisear", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/23.png', imageLarge: 'https://images.pokemontcg.io/sv8/23_hires.png' },
      { id: 24, name: "Larvesta", type: 'fire', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/24.png', imageLarge: 'https://images.pokemontcg.io/sv8/24_hires.png' },
      { id: 25, name: "Volcarona", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/25.png', imageLarge: 'https://images.pokemontcg.io/sv8/25_hires.png' },
      { id: 26, name: "Oricorio", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/26.png', imageLarge: 'https://images.pokemontcg.io/sv8/26_hires.png' },
      { id: 27, name: "Sizzlipede", type: 'fire', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/27.png', imageLarge: 'https://images.pokemontcg.io/sv8/27_hires.png' },
      { id: 28, name: "Centiskorch", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/28.png', imageLarge: 'https://images.pokemontcg.io/sv8/28_hires.png' },
      { id: 29, name: "Fuecoco", type: 'fire', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/29.png', imageLarge: 'https://images.pokemontcg.io/sv8/29_hires.png' },
      { id: 30, name: "Crocalor", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/30.png', imageLarge: 'https://images.pokemontcg.io/sv8/30_hires.png' },
      { id: 31, name: "Skeledirge", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/31.png', imageLarge: 'https://images.pokemontcg.io/sv8/31_hires.png' },
      { id: 32, name: "Charcadet", type: 'fire', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/32.png', imageLarge: 'https://images.pokemontcg.io/sv8/32_hires.png' },
      { id: 33, name: "Charcadet", type: 'fire', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/33.png', imageLarge: 'https://images.pokemontcg.io/sv8/33_hires.png' },
      { id: 34, name: "Armarouge", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/34.png', imageLarge: 'https://images.pokemontcg.io/sv8/34_hires.png' },
      { id: 35, name: "Ceruledge", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/35.png', imageLarge: 'https://images.pokemontcg.io/sv8/35_hires.png' },
      { id: 36, name: "Ceruledge ex", type: 'fire', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/36.png', imageLarge: 'https://images.pokemontcg.io/sv8/36_hires.png' },
      { id: 37, name: "Scovillain ex", type: 'fire', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/37.png', imageLarge: 'https://images.pokemontcg.io/sv8/37_hires.png' },
      { id: 38, name: "Gouging Fire", type: 'fire', rarity: 'R', imageSmall: 'https://images.pokemontcg.io/sv8/38.png', imageLarge: 'https://images.pokemontcg.io/sv8/38_hires.png' },
      { id: 39, name: "Paldean Tauros", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/39.png', imageLarge: 'https://images.pokemontcg.io/sv8/39_hires.png' },
      { id: 40, name: "Mantine", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/40.png', imageLarge: 'https://images.pokemontcg.io/sv8/40_hires.png' },
      { id: 41, name: "Feebas", type: 'water', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/41.png', imageLarge: 'https://images.pokemontcg.io/sv8/41_hires.png' },
      { id: 42, name: "Milotic ex", type: 'water', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/42.png', imageLarge: 'https://images.pokemontcg.io/sv8/42_hires.png' },
      { id: 43, name: "Spheal", type: 'water', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/43.png', imageLarge: 'https://images.pokemontcg.io/sv8/43_hires.png' },
      { id: 44, name: "Sealeo", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/44.png', imageLarge: 'https://images.pokemontcg.io/sv8/44_hires.png' },
      { id: 45, name: "Walrein", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/45.png', imageLarge: 'https://images.pokemontcg.io/sv8/45_hires.png' },
      { id: 46, name: "Shellos", type: 'water', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/46.png', imageLarge: 'https://images.pokemontcg.io/sv8/46_hires.png' },
      { id: 47, name: "Cryogonal", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/47.png', imageLarge: 'https://images.pokemontcg.io/sv8/47_hires.png' },
      { id: 48, name: "Black Kyurem ex", type: 'water', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/48.png', imageLarge: 'https://images.pokemontcg.io/sv8/48_hires.png' },
      { id: 49, name: "Bruxish", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/49.png', imageLarge: 'https://images.pokemontcg.io/sv8/49_hires.png' },
      { id: 50, name: "Quaxly", type: 'water', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/50.png', imageLarge: 'https://images.pokemontcg.io/sv8/50_hires.png' },
      { id: 51, name: "Quaxwell", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/51.png', imageLarge: 'https://images.pokemontcg.io/sv8/51_hires.png' },
      { id: 52, name: "Quaquaval", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/52.png', imageLarge: 'https://images.pokemontcg.io/sv8/52_hires.png' },
      { id: 53, name: "Cetoddle", type: 'water', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/53.png', imageLarge: 'https://images.pokemontcg.io/sv8/53_hires.png' },
      { id: 54, name: "Cetitan", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/54.png', imageLarge: 'https://images.pokemontcg.io/sv8/54_hires.png' },
      { id: 55, name: "Iron Bundle", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/55.png', imageLarge: 'https://images.pokemontcg.io/sv8/55_hires.png' },
      { id: 56, name: "Chien-Pao", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/56.png', imageLarge: 'https://images.pokemontcg.io/sv8/56_hires.png' },
      { id: 57, name: "Pikachu ex", type: 'lightning', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/57.png', imageLarge: 'https://images.pokemontcg.io/sv8/57_hires.png' },
      { id: 58, name: "Magnemite", type: 'steel', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/58.png', imageLarge: 'https://images.pokemontcg.io/sv8/58_hires.png' },
      { id: 59, name: "Magneton", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/59.png', imageLarge: 'https://images.pokemontcg.io/sv8/59_hires.png' },
      { id: 60, name: "Magnezone", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/60.png', imageLarge: 'https://images.pokemontcg.io/sv8/60_hires.png' },
      { id: 61, name: "Rotom", type: 'lightning', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/61.png', imageLarge: 'https://images.pokemontcg.io/sv8/61_hires.png' },
      { id: 62, name: "Blitzle", type: 'lightning', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/62.png', imageLarge: 'https://images.pokemontcg.io/sv8/62_hires.png' },
      { id: 63, name: "Zebstrika", type: 'lightning', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/63.png', imageLarge: 'https://images.pokemontcg.io/sv8/63_hires.png' },
      { id: 64, name: "Stunfisk", type: 'lightning', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/64.png', imageLarge: 'https://images.pokemontcg.io/sv8/64_hires.png' },
      { id: 65, name: "Tapu Koko", type: 'lightning', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/65.png', imageLarge: 'https://images.pokemontcg.io/sv8/65_hires.png' },
      { id: 66, name: "Wattrel", type: 'lightning', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/66.png', imageLarge: 'https://images.pokemontcg.io/sv8/66_hires.png' },
      { id: 67, name: "Kilowattrel", type: 'lightning', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/67.png', imageLarge: 'https://images.pokemontcg.io/sv8/67_hires.png' },
      { id: 68, name: "Kilowattrel ex", type: 'lightning', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/68.png', imageLarge: 'https://images.pokemontcg.io/sv8/68_hires.png' },
      { id: 69, name: "Miraidon", type: 'lightning', rarity: 'R', imageSmall: 'https://images.pokemontcg.io/sv8/69.png', imageLarge: 'https://images.pokemontcg.io/sv8/69_hires.png' },
      { id: 70, name: "Togepi", type: 'psychic', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/70.png', imageLarge: 'https://images.pokemontcg.io/sv8/70_hires.png' },
      { id: 71, name: "Togetic", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/71.png', imageLarge: 'https://images.pokemontcg.io/sv8/71_hires.png' },
      { id: 72, name: "Togekiss", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/72.png', imageLarge: 'https://images.pokemontcg.io/sv8/72_hires.png' },
      { id: 73, name: "Marill", type: 'water', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/73.png', imageLarge: 'https://images.pokemontcg.io/sv8/73_hires.png' },
      { id: 74, name: "Azumarill", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/74.png', imageLarge: 'https://images.pokemontcg.io/sv8/74_hires.png' },
      { id: 75, name: "Smoochum", type: 'psychic', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/75.png', imageLarge: 'https://images.pokemontcg.io/sv8/75_hires.png' },
      { id: 76, name: "Latias ex", type: 'psychic', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/76.png', imageLarge: 'https://images.pokemontcg.io/sv8/76_hires.png' },
      { id: 77, name: "Latios", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/77.png', imageLarge: 'https://images.pokemontcg.io/sv8/77_hires.png' },
      { id: 78, name: "Uxie", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/78.png', imageLarge: 'https://images.pokemontcg.io/sv8/78_hires.png' },
      { id: 79, name: "Mesprit", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/79.png', imageLarge: 'https://images.pokemontcg.io/sv8/79_hires.png' },
      { id: 80, name: "Azelf", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/80.png', imageLarge: 'https://images.pokemontcg.io/sv8/80_hires.png' },
      { id: 81, name: "Sigilyph", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/81.png', imageLarge: 'https://images.pokemontcg.io/sv8/81_hires.png' },
      { id: 82, name: "Yamask", type: 'psychic', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/82.png', imageLarge: 'https://images.pokemontcg.io/sv8/82_hires.png' },
      { id: 83, name: "Cofagrigus", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/83.png', imageLarge: 'https://images.pokemontcg.io/sv8/83_hires.png' },
      { id: 84, name: "Espurr", type: 'psychic', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/84.png', imageLarge: 'https://images.pokemontcg.io/sv8/84_hires.png' },
      { id: 85, name: "Meowstic", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/85.png', imageLarge: 'https://images.pokemontcg.io/sv8/85_hires.png' },
      { id: 86, name: "Sylveon ex", type: 'psychic', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/86.png', imageLarge: 'https://images.pokemontcg.io/sv8/86_hires.png' },
      { id: 87, name: "Dedenne", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/87.png', imageLarge: 'https://images.pokemontcg.io/sv8/87_hires.png' },
      { id: 88, name: "Xerneas", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/88.png', imageLarge: 'https://images.pokemontcg.io/sv8/88_hires.png' },
      { id: 89, name: "Oricorio", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/89.png', imageLarge: 'https://images.pokemontcg.io/sv8/89_hires.png' },
      { id: 90, name: "Sandygast", type: 'psychic', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/90.png', imageLarge: 'https://images.pokemontcg.io/sv8/90_hires.png' },
      { id: 91, name: "Palossand ex", type: 'psychic', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/91.png', imageLarge: 'https://images.pokemontcg.io/sv8/91_hires.png' },
      { id: 92, name: "Tapu Lele", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/92.png', imageLarge: 'https://images.pokemontcg.io/sv8/92_hires.png' },
      { id: 93, name: "Indeedee", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/93.png', imageLarge: 'https://images.pokemontcg.io/sv8/93_hires.png' },
      { id: 94, name: "Flittle", type: 'psychic', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/94.png', imageLarge: 'https://images.pokemontcg.io/sv8/94_hires.png' },
      { id: 95, name: "Espathra", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/95.png', imageLarge: 'https://images.pokemontcg.io/sv8/95_hires.png' },
      { id: 96, name: "Flutter Mane", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/96.png', imageLarge: 'https://images.pokemontcg.io/sv8/96_hires.png' },
      { id: 97, name: "Gimmighoul", type: 'psychic', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/97.png', imageLarge: 'https://images.pokemontcg.io/sv8/97_hires.png' },
      { id: 98, name: "Mankey", type: 'fighting', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/98.png', imageLarge: 'https://images.pokemontcg.io/sv8/98_hires.png' },
      { id: 99, name: "Primeape", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/99.png', imageLarge: 'https://images.pokemontcg.io/sv8/99_hires.png' },
      { id: 100, name: "Annihilape", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/100.png', imageLarge: 'https://images.pokemontcg.io/sv8/100_hires.png' },
      { id: 101, name: "Paldean Tauros", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/101.png', imageLarge: 'https://images.pokemontcg.io/sv8/101_hires.png' },
      { id: 102, name: "Phanpy", type: 'fighting', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/102.png', imageLarge: 'https://images.pokemontcg.io/sv8/102_hires.png' },
      { id: 103, name: "Donphan", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/103.png', imageLarge: 'https://images.pokemontcg.io/sv8/103_hires.png' },
      { id: 104, name: "Trapinch", type: 'fighting', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/104.png', imageLarge: 'https://images.pokemontcg.io/sv8/104_hires.png' },
      { id: 105, name: "Vibrava", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/105.png', imageLarge: 'https://images.pokemontcg.io/sv8/105_hires.png' },
      { id: 106, name: "Flygon ex", type: 'fighting', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/106.png', imageLarge: 'https://images.pokemontcg.io/sv8/106_hires.png' },
      { id: 107, name: "Gastrodon", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/107.png', imageLarge: 'https://images.pokemontcg.io/sv8/107_hires.png' },
      { id: 108, name: "Drilbur", type: 'fighting', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/108.png', imageLarge: 'https://images.pokemontcg.io/sv8/108_hires.png' },
      { id: 109, name: "Excadrill", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/109.png', imageLarge: 'https://images.pokemontcg.io/sv8/109_hires.png' },
      { id: 110, name: "Landorus", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/110.png', imageLarge: 'https://images.pokemontcg.io/sv8/110_hires.png' },
      { id: 111, name: "Passimian", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/111.png', imageLarge: 'https://images.pokemontcg.io/sv8/111_hires.png' },
      { id: 112, name: "Clobbopus", type: 'fighting', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/112.png', imageLarge: 'https://images.pokemontcg.io/sv8/112_hires.png' },
      { id: 113, name: "Grapploct", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/113.png', imageLarge: 'https://images.pokemontcg.io/sv8/113_hires.png' },
      { id: 114, name: "Glimmet", type: 'fighting', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/114.png', imageLarge: 'https://images.pokemontcg.io/sv8/114_hires.png' },
      { id: 115, name: "Glimmora", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/115.png', imageLarge: 'https://images.pokemontcg.io/sv8/115_hires.png' },
      { id: 116, name: "Koraidon", type: 'fighting', rarity: 'R', imageSmall: 'https://images.pokemontcg.io/sv8/116.png', imageLarge: 'https://images.pokemontcg.io/sv8/116_hires.png' },
      { id: 117, name: "Deino", type: 'dragon', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/117.png', imageLarge: 'https://images.pokemontcg.io/sv8/117_hires.png' },
      { id: 118, name: "Zweilous", type: 'dragon', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/118.png', imageLarge: 'https://images.pokemontcg.io/sv8/118_hires.png' },
      { id: 119, name: "Hydreigon ex", type: 'dragon', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/119.png', imageLarge: 'https://images.pokemontcg.io/sv8/119_hires.png' },
      { id: 120, name: "Shroodle", type: 'dark', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/120.png', imageLarge: 'https://images.pokemontcg.io/sv8/120_hires.png' },
      { id: 121, name: "Grafaiai", type: 'dark', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/121.png', imageLarge: 'https://images.pokemontcg.io/sv8/121_hires.png' },
      { id: 122, name: "Alolan Diglett", type: 'steel', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/122.png', imageLarge: 'https://images.pokemontcg.io/sv8/122_hires.png' },
      { id: 123, name: "Alolan Dugtrio", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/123.png', imageLarge: 'https://images.pokemontcg.io/sv8/123_hires.png' },
      { id: 124, name: "Skarmory", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/124.png', imageLarge: 'https://images.pokemontcg.io/sv8/124_hires.png' },
      { id: 125, name: "Registeel", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/125.png', imageLarge: 'https://images.pokemontcg.io/sv8/125_hires.png' },
      { id: 126, name: "Bronzor", type: 'steel', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/126.png', imageLarge: 'https://images.pokemontcg.io/sv8/126_hires.png' },
      { id: 127, name: "Bronzong", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/127.png', imageLarge: 'https://images.pokemontcg.io/sv8/127_hires.png' },
      { id: 128, name: "Klefki", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/128.png', imageLarge: 'https://images.pokemontcg.io/sv8/128_hires.png' },
      { id: 129, name: "Duraludon", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/129.png', imageLarge: 'https://images.pokemontcg.io/sv8/129_hires.png' },
      { id: 130, name: "Archaludon ex", type: 'steel', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/130.png', imageLarge: 'https://images.pokemontcg.io/sv8/130_hires.png' },
      { id: 131, name: "Gholdengo", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/131.png', imageLarge: 'https://images.pokemontcg.io/sv8/131_hires.png' },
      { id: 132, name: "Iron Crown", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/132.png', imageLarge: 'https://images.pokemontcg.io/sv8/132_hires.png' },
      { id: 133, name: "Alolan Exeggutor ex", type: 'grass', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/133.png', imageLarge: 'https://images.pokemontcg.io/sv8/133_hires.png' },
      { id: 134, name: "Altaria", type: 'dragon', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/134.png', imageLarge: 'https://images.pokemontcg.io/sv8/134_hires.png' },
      { id: 135, name: "Dialga", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/135.png', imageLarge: 'https://images.pokemontcg.io/sv8/135_hires.png' },
      { id: 136, name: "Palkia", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/136.png', imageLarge: 'https://images.pokemontcg.io/sv8/136_hires.png' },
      { id: 137, name: "Turtonator", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/137.png', imageLarge: 'https://images.pokemontcg.io/sv8/137_hires.png' },
      { id: 138, name: "Applin", type: 'grass', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/138.png', imageLarge: 'https://images.pokemontcg.io/sv8/138_hires.png' },
      { id: 139, name: "Flapple", type: 'grass', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/139.png', imageLarge: 'https://images.pokemontcg.io/sv8/139_hires.png' },
      { id: 140, name: "Appletun", type: 'grass', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/140.png', imageLarge: 'https://images.pokemontcg.io/sv8/140_hires.png' },
      { id: 141, name: "Eternatus", type: 'dark', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/141.png', imageLarge: 'https://images.pokemontcg.io/sv8/141_hires.png' },
      { id: 142, name: "Tatsugiri ex", type: 'water', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/142.png', imageLarge: 'https://images.pokemontcg.io/sv8/142_hires.png' },
      { id: 143, name: "Eevee", type: 'normal', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/143.png', imageLarge: 'https://images.pokemontcg.io/sv8/143_hires.png' },
      { id: 144, name: "Snorlax", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/144.png', imageLarge: 'https://images.pokemontcg.io/sv8/144_hires.png' },
      { id: 145, name: "Slakoth", type: 'normal', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/145.png', imageLarge: 'https://images.pokemontcg.io/sv8/145_hires.png' },
      { id: 146, name: "Vigoroth", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/146.png', imageLarge: 'https://images.pokemontcg.io/sv8/146_hires.png' },
      { id: 147, name: "Slaking ex", type: 'normal', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/147.png', imageLarge: 'https://images.pokemontcg.io/sv8/147_hires.png' },
      { id: 148, name: "Zangoose", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/148.png', imageLarge: 'https://images.pokemontcg.io/sv8/148_hires.png' },
      { id: 149, name: "Kecleon", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/149.png', imageLarge: 'https://images.pokemontcg.io/sv8/149_hires.png' },
      { id: 150, name: "Bouffalant", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/150.png', imageLarge: 'https://images.pokemontcg.io/sv8/150_hires.png' },
      { id: 151, name: "Swablu", type: 'normal', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/151.png', imageLarge: 'https://images.pokemontcg.io/sv8/151_hires.png' },
      { id: 152, name: "Rufflet", type: 'normal', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/152.png', imageLarge: 'https://images.pokemontcg.io/sv8/152_hires.png' },
      { id: 153, name: "Braviary", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/153.png', imageLarge: 'https://images.pokemontcg.io/sv8/153_hires.png' },
      { id: 154, name: "Helioptile", type: 'normal', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/154.png', imageLarge: 'https://images.pokemontcg.io/sv8/154_hires.png' },
      { id: 155, name: "Heliolisk", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/155.png', imageLarge: 'https://images.pokemontcg.io/sv8/155_hires.png' },
      { id: 156, name: "Oranguru", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/156.png', imageLarge: 'https://images.pokemontcg.io/sv8/156_hires.png' },
      { id: 157, name: "Tandemaus", type: 'normal', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8/157.png', imageLarge: 'https://images.pokemontcg.io/sv8/157_hires.png' },
      { id: 158, name: "Maushold", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/158.png', imageLarge: 'https://images.pokemontcg.io/sv8/158_hires.png' },
      { id: 159, name: "Cyclizar ex", type: 'normal', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/159.png', imageLarge: 'https://images.pokemontcg.io/sv8/159_hires.png' },
      { id: 160, name: "Flamigo ex", type: 'normal', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8/160.png', imageLarge: 'https://images.pokemontcg.io/sv8/160_hires.png' },
      { id: 161, name: "Terapagos", type: 'normal', rarity: 'R', imageSmall: 'https://images.pokemontcg.io/sv8/161.png', imageLarge: 'https://images.pokemontcg.io/sv8/161_hires.png' },
      { id: 162, name: "Amulet of Hope", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/162.png', imageLarge: 'https://images.pokemontcg.io/sv8/162_hires.png' },
      { id: 163, name: "Babiri Berry", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/163.png', imageLarge: 'https://images.pokemontcg.io/sv8/163_hires.png' },
      { id: 164, name: "Brilliant Blender", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/164.png', imageLarge: 'https://images.pokemontcg.io/sv8/164_hires.png' },
      { id: 165, name: "Call Bell", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/165.png', imageLarge: 'https://images.pokemontcg.io/sv8/165_hires.png' },
      { id: 166, name: "Chill Teaser Toy", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/166.png', imageLarge: 'https://images.pokemontcg.io/sv8/166_hires.png' },
      { id: 167, name: "Clemont's Quick Wit", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/167.png', imageLarge: 'https://images.pokemontcg.io/sv8/167_hires.png' },
      { id: 168, name: "Colbur Berry", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/168.png', imageLarge: 'https://images.pokemontcg.io/sv8/168_hires.png' },
      { id: 169, name: "Counter Gain", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/169.png', imageLarge: 'https://images.pokemontcg.io/sv8/169_hires.png' },
      { id: 170, name: "Cyrano", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/170.png', imageLarge: 'https://images.pokemontcg.io/sv8/170_hires.png' },
      { id: 171, name: "Deduction Kit", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/171.png', imageLarge: 'https://images.pokemontcg.io/sv8/171_hires.png' },
      { id: 172, name: "Dragon Elixir", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/172.png', imageLarge: 'https://images.pokemontcg.io/sv8/172_hires.png' },
      { id: 173, name: "Drasna", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/173.png', imageLarge: 'https://images.pokemontcg.io/sv8/173_hires.png' },
      { id: 174, name: "Drayton", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/174.png', imageLarge: 'https://images.pokemontcg.io/sv8/174_hires.png' },
      { id: 175, name: "Dusk Ball", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/175.png', imageLarge: 'https://images.pokemontcg.io/sv8/175_hires.png' },
      { id: 176, name: "Energy Search Pro", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/176.png', imageLarge: 'https://images.pokemontcg.io/sv8/176_hires.png' },
      { id: 177, name: "Gravity Mountain", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/177.png', imageLarge: 'https://images.pokemontcg.io/sv8/177_hires.png' },
      { id: 178, name: "Jasmine's Gaze", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/178.png', imageLarge: 'https://images.pokemontcg.io/sv8/178_hires.png' },
      { id: 179, name: "Lisia's Appeal", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/179.png', imageLarge: 'https://images.pokemontcg.io/sv8/179_hires.png' },
      { id: 180, name: "Lively Stadium", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/180.png', imageLarge: 'https://images.pokemontcg.io/sv8/180_hires.png' },
      { id: 181, name: "Meddling Memo", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/181.png', imageLarge: 'https://images.pokemontcg.io/sv8/181_hires.png' },
      { id: 182, name: "Megaton Blower", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/182.png', imageLarge: 'https://images.pokemontcg.io/sv8/182_hires.png' },
      { id: 183, name: "Miracle Headset", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/183.png', imageLarge: 'https://images.pokemontcg.io/sv8/183_hires.png' },
      { id: 184, name: "Passho Berry", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/184.png', imageLarge: 'https://images.pokemontcg.io/sv8/184_hires.png' },
      { id: 185, name: "Precious Trolley", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/185.png', imageLarge: 'https://images.pokemontcg.io/sv8/185_hires.png' },
      { id: 186, name: "Scramble Switch", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/186.png', imageLarge: 'https://images.pokemontcg.io/sv8/186_hires.png' },
      { id: 187, name: "Surfer", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/187.png', imageLarge: 'https://images.pokemontcg.io/sv8/187_hires.png' },
      { id: 188, name: "TM: Fluorite", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/188.png', imageLarge: 'https://images.pokemontcg.io/sv8/188_hires.png' },
      { id: 189, name: "Tera Orb", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/189.png', imageLarge: 'https://images.pokemontcg.io/sv8/189_hires.png' },
      { id: 190, name: "Tyme", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/190.png', imageLarge: 'https://images.pokemontcg.io/sv8/190_hires.png' },
      { id: 191, name: "Enriching Energy", type: 'energy', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8/191.png', imageLarge: 'https://images.pokemontcg.io/sv8/191_hires.png' },
      { id: 192, name: "Exeggcute", type: 'grass', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/192.png', imageLarge: 'https://images.pokemontcg.io/sv8/192_hires.png' },
      { id: 193, name: "Vivillon", type: 'grass', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/193.png', imageLarge: 'https://images.pokemontcg.io/sv8/193_hires.png' },
      { id: 194, name: "Shiinotic", type: 'grass', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/194.png', imageLarge: 'https://images.pokemontcg.io/sv8/194_hires.png' },
      { id: 195, name: "Castform Sunny Form", type: 'fire', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/195.png', imageLarge: 'https://images.pokemontcg.io/sv8/195_hires.png' },
      { id: 196, name: "Larvesta", type: 'fire', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/196.png', imageLarge: 'https://images.pokemontcg.io/sv8/196_hires.png' },
      { id: 197, name: "Ceruledge", type: 'fire', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/197.png', imageLarge: 'https://images.pokemontcg.io/sv8/197_hires.png' },
      { id: 198, name: "Feebas", type: 'water', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/198.png', imageLarge: 'https://images.pokemontcg.io/sv8/198_hires.png' },
      { id: 199, name: "Spheal", type: 'water', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/199.png', imageLarge: 'https://images.pokemontcg.io/sv8/199_hires.png' },
      { id: 200, name: "Bruxish", type: 'water', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/200.png', imageLarge: 'https://images.pokemontcg.io/sv8/200_hires.png' },
      { id: 201, name: "Cetitan", type: 'water', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/201.png', imageLarge: 'https://images.pokemontcg.io/sv8/201_hires.png' },
      { id: 202, name: "Stunfisk", type: 'lightning', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/202.png', imageLarge: 'https://images.pokemontcg.io/sv8/202_hires.png' },
      { id: 203, name: "Latios", type: 'psychic', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/203.png', imageLarge: 'https://images.pokemontcg.io/sv8/203_hires.png' },
      { id: 204, name: "Mesprit", type: 'psychic', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/204.png', imageLarge: 'https://images.pokemontcg.io/sv8/204_hires.png' },
      { id: 205, name: "Phanpy", type: 'fighting', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/205.png', imageLarge: 'https://images.pokemontcg.io/sv8/205_hires.png' },
      { id: 206, name: "Vibrava", type: 'fighting', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/206.png', imageLarge: 'https://images.pokemontcg.io/sv8/206_hires.png' },
      { id: 207, name: "Clobbopus", type: 'fighting', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/207.png', imageLarge: 'https://images.pokemontcg.io/sv8/207_hires.png' },
      { id: 208, name: "Alolan Dugtrio", type: 'steel', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/208.png', imageLarge: 'https://images.pokemontcg.io/sv8/208_hires.png' },
      { id: 209, name: "Skarmory", type: 'steel', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/209.png', imageLarge: 'https://images.pokemontcg.io/sv8/209_hires.png' },
      { id: 210, name: "Flapple", type: 'grass', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/210.png', imageLarge: 'https://images.pokemontcg.io/sv8/210_hires.png' },
      { id: 211, name: "Appletun", type: 'grass', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/211.png', imageLarge: 'https://images.pokemontcg.io/sv8/211_hires.png' },
      { id: 212, name: "Slakoth", type: 'normal', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/212.png', imageLarge: 'https://images.pokemontcg.io/sv8/212_hires.png' },
      { id: 213, name: "Kecleon", type: 'normal', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/213.png', imageLarge: 'https://images.pokemontcg.io/sv8/213_hires.png' },
      { id: 214, name: "Braviary", type: 'normal', rarity: 'AR', imageSmall: 'https://images.pokemontcg.io/sv8/214.png', imageLarge: 'https://images.pokemontcg.io/sv8/214_hires.png' },
      { id: 215, name: "Durant ex", type: 'steel', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/215.png', imageLarge: 'https://images.pokemontcg.io/sv8/215_hires.png' },
      { id: 216, name: "Scovillain ex", type: 'fire', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/216.png', imageLarge: 'https://images.pokemontcg.io/sv8/216_hires.png' },
      { id: 217, name: "Milotic ex", type: 'water', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/217.png', imageLarge: 'https://images.pokemontcg.io/sv8/217_hires.png' },
      { id: 218, name: "Black Kyurem ex", type: 'water', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/218.png', imageLarge: 'https://images.pokemontcg.io/sv8/218_hires.png' },
      { id: 219, name: "Pikachu ex", type: 'lightning', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/219.png', imageLarge: 'https://images.pokemontcg.io/sv8/219_hires.png' },
      { id: 220, name: "Latias ex", type: 'psychic', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/220.png', imageLarge: 'https://images.pokemontcg.io/sv8/220_hires.png' },
      { id: 221, name: "Palossand ex", type: 'psychic', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/221.png', imageLarge: 'https://images.pokemontcg.io/sv8/221_hires.png' },
      { id: 222, name: "Flygon ex", type: 'fighting', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/222.png', imageLarge: 'https://images.pokemontcg.io/sv8/222_hires.png' },
      { id: 223, name: "Hydreigon ex", type: 'dragon', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/223.png', imageLarge: 'https://images.pokemontcg.io/sv8/223_hires.png' },
      { id: 224, name: "Archaludon ex", type: 'steel', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/224.png', imageLarge: 'https://images.pokemontcg.io/sv8/224_hires.png' },
      { id: 225, name: "Alolan Exeggutor ex", type: 'grass', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/225.png', imageLarge: 'https://images.pokemontcg.io/sv8/225_hires.png' },
      { id: 226, name: "Tatsugiri ex", type: 'water', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/226.png', imageLarge: 'https://images.pokemontcg.io/sv8/226_hires.png' },
      { id: 227, name: "Slaking ex", type: 'normal', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/227.png', imageLarge: 'https://images.pokemontcg.io/sv8/227_hires.png' },
      { id: 228, name: "Cyclizar ex", type: 'normal', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/228.png', imageLarge: 'https://images.pokemontcg.io/sv8/228_hires.png' },
      { id: 229, name: "Clemont's Quick Wit", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/229.png', imageLarge: 'https://images.pokemontcg.io/sv8/229_hires.png' },
      { id: 230, name: "Cyrano", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/230.png', imageLarge: 'https://images.pokemontcg.io/sv8/230_hires.png' },
      { id: 231, name: "Drasna", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/231.png', imageLarge: 'https://images.pokemontcg.io/sv8/231_hires.png' },
      { id: 232, name: "Drayton", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/232.png', imageLarge: 'https://images.pokemontcg.io/sv8/232_hires.png' },
      { id: 233, name: "Jasmine's Gaze", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/233.png', imageLarge: 'https://images.pokemontcg.io/sv8/233_hires.png' },
      { id: 234, name: "Lisia's Appeal", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/234.png', imageLarge: 'https://images.pokemontcg.io/sv8/234_hires.png' },
      { id: 235, name: "Surfer", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8/235.png', imageLarge: 'https://images.pokemontcg.io/sv8/235_hires.png' },
      { id: 236, name: "Durant ex", type: 'steel', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8/236.png', imageLarge: 'https://images.pokemontcg.io/sv8/236_hires.png' },
      { id: 237, name: "Milotic ex", type: 'water', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8/237.png', imageLarge: 'https://images.pokemontcg.io/sv8/237_hires.png' },
      { id: 238, name: "Pikachu ex", type: 'lightning', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8/238.png', imageLarge: 'https://images.pokemontcg.io/sv8/238_hires.png' },
      { id: 239, name: "Latias ex", type: 'psychic', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8/239.png', imageLarge: 'https://images.pokemontcg.io/sv8/239_hires.png' },
      { id: 240, name: "Hydreigon ex", type: 'dragon', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8/240.png', imageLarge: 'https://images.pokemontcg.io/sv8/240_hires.png' },
      { id: 241, name: "Archaludon ex", type: 'steel', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8/241.png', imageLarge: 'https://images.pokemontcg.io/sv8/241_hires.png' },
      { id: 242, name: "Alolan Exeggutor ex", type: 'grass', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8/242.png', imageLarge: 'https://images.pokemontcg.io/sv8/242_hires.png' },
      { id: 243, name: "Clemont's Quick Wit", type: 'trainer', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8/243.png', imageLarge: 'https://images.pokemontcg.io/sv8/243_hires.png' },
      { id: 244, name: "Drayton", type: 'trainer', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8/244.png', imageLarge: 'https://images.pokemontcg.io/sv8/244_hires.png' },
      { id: 245, name: "Jasmine's Gaze", type: 'trainer', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8/245.png', imageLarge: 'https://images.pokemontcg.io/sv8/245_hires.png' },
      { id: 246, name: "Lisia's Appeal", type: 'trainer', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8/246.png', imageLarge: 'https://images.pokemontcg.io/sv8/246_hires.png' },
      { id: 247, name: "Pikachu ex", type: 'lightning', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8/247.png', imageLarge: 'https://images.pokemontcg.io/sv8/247_hires.png' },
      { id: 248, name: "Alolan Exeggutor ex", type: 'grass', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8/248.png', imageLarge: 'https://images.pokemontcg.io/sv8/248_hires.png' },
      { id: 249, name: "Counter Gain", type: 'trainer', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8/249.png', imageLarge: 'https://images.pokemontcg.io/sv8/249_hires.png' },
      { id: 250, name: "Gravity Mountain", type: 'trainer', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8/250.png', imageLarge: 'https://images.pokemontcg.io/sv8/250_hires.png' },
      { id: 251, name: "Night Stretcher", type: 'trainer', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8/251.png', imageLarge: 'https://images.pokemontcg.io/sv8/251_hires.png' },
      { id: 252, name: "Jet Energy", type: 'energy', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8/252.png', imageLarge: 'https://images.pokemontcg.io/sv8/252_hires.png' },
    ]
  },
  'sv8pt5': {
    info: {
      id: 'sv8pt5',
      name: 'Prismatic Evolutions',
      nameKo: '프리즈매틱 에볼루션',
      fullName: 'Scarlet & Violet — Prismatic Evolutions',
      totalCards: 180,
      baseCards: 131,
      releaseDate: '2025-01-17',
      cardsPerPack: 10,
      price: 1500,
      packImage: 'assets/sv8pt5_pack.jpg',
      maxImageId: 180,
      coverColor: 'linear-gradient(135deg, #a855f7, #ec4899, #f59e0b)'
    },
    cards: [
      { id: 1, name: "Exeggcute", type: 'grass', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/1.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/1_hires.png' },
      { id: 2, name: "Exeggutor", type: 'grass', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/2.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/2_hires.png' },
      { id: 3, name: "Pinsir", type: 'grass', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/3.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/3_hires.png' },
      { id: 4, name: "Budew", type: 'grass', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/4.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/4_hires.png' },
      { id: 5, name: "Leafeon", type: 'grass', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/5.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/5_hires.png' },
      { id: 6, name: "Leafeon ex", type: 'grass', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/6.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/6_hires.png' },
      { id: 7, name: "Cottonee", type: 'grass', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/7.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/7_hires.png' },
      { id: 8, name: "Whimsicott", type: 'grass', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/8.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/8_hires.png' },
      { id: 9, name: "Applin", type: 'grass', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/9.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/9_hires.png' },
      { id: 10, name: "Dipplin", type: 'grass', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/10.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/10_hires.png' },
      { id: 11, name: "Hydrapple ex", type: 'grass', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/11.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/11_hires.png' },
      { id: 12, name: "Teal Mask Ogerpon ex", type: 'grass', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/12.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/12_hires.png' },
      { id: 13, name: "Flareon", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/13.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/13_hires.png' },
      { id: 14, name: "Flareon ex", type: 'fire', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/14.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/14_hires.png' },
      { id: 15, name: "Litleo", type: 'fire', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/15.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/15_hires.png' },
      { id: 16, name: "Pyroar", type: 'fire', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/16.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/16_hires.png' },
      { id: 17, name: "Hearthflame Mask Ogerpon ex", type: 'fire', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/17.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/17_hires.png' },
      { id: 18, name: "Slowpoke", type: 'water', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/18.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/18_hires.png' },
      { id: 19, name: "Slowking", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/19.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/19_hires.png' },
      { id: 20, name: "Goldeen", type: 'water', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/20.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/20_hires.png' },
      { id: 21, name: "Seaking", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/21.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/21_hires.png' },
      { id: 22, name: "Vaporeon", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/22.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/22_hires.png' },
      { id: 23, name: "Vaporeon ex", type: 'water', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/23.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/23_hires.png' },
      { id: 24, name: "Suicune", type: 'water', rarity: 'R', imageSmall: 'https://images.pokemontcg.io/sv8pt5/24.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/24_hires.png' },
      { id: 25, name: "Glaceon", type: 'water', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/25.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/25_hires.png' },
      { id: 26, name: "Glaceon ex", type: 'water', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/26.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/26_hires.png' },
      { id: 27, name: "Wellspring Mask Ogerpon ex", type: 'water', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/27.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/27_hires.png' },
      { id: 28, name: "Pikachu ex", type: 'lightning', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/28.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/28_hires.png' },
      { id: 29, name: "Jolteon", type: 'lightning', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/29.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/29_hires.png' },
      { id: 30, name: "Jolteon ex", type: 'lightning', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/30.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/30_hires.png' },
      { id: 31, name: "Iron Hands ex", type: 'lightning', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/31.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/31_hires.png' },
      { id: 32, name: "Iron Thorns ex", type: 'lightning', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/32.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/32_hires.png' },
      { id: 33, name: "Espeon", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/33.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/33_hires.png' },
      { id: 34, name: "Espeon ex", type: 'psychic', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/34.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/34_hires.png' },
      { id: 35, name: "Duskull", type: 'psychic', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/35.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/35_hires.png' },
      { id: 36, name: "Dusclops", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/36.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/36_hires.png' },
      { id: 37, name: "Dusknoir", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/37.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/37_hires.png' },
      { id: 38, name: "Spritzee", type: 'psychic', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/38.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/38_hires.png' },
      { id: 39, name: "Aromatisse", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/39.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/39_hires.png' },
      { id: 40, name: "Sylveon", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/40.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/40_hires.png' },
      { id: 41, name: "Sylveon ex", type: 'psychic', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/41.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/41_hires.png' },
      { id: 42, name: "Scream Tail", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/42.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/42_hires.png' },
      { id: 43, name: "Flutter Mane", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/43.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/43_hires.png' },
      { id: 44, name: "Munkidori", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/44.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/44_hires.png' },
      { id: 45, name: "Fezandipiti", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/45.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/45_hires.png' },
      { id: 46, name: "Iron Boulder", type: 'psychic', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/46.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/46_hires.png' },
      { id: 47, name: "Larvitar", type: 'fighting', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/47.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/47_hires.png' },
      { id: 48, name: "Pupitar", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/48.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/48_hires.png' },
      { id: 49, name: "Groudon", type: 'fighting', rarity: 'R', imageSmall: 'https://images.pokemontcg.io/sv8pt5/49.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/49_hires.png' },
      { id: 50, name: "Riolu", type: 'fighting', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/50.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/50_hires.png' },
      { id: 51, name: "Lucario ex", type: 'fighting', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/51.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/51_hires.png' },
      { id: 52, name: "Hippopotas", type: 'fighting', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/52.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/52_hires.png' },
      { id: 53, name: "Hippowdon", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/53.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/53_hires.png' },
      { id: 54, name: "Bloodmoon Ursaluna", type: 'fighting', rarity: 'R', imageSmall: 'https://images.pokemontcg.io/sv8pt5/54.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/54_hires.png' },
      { id: 55, name: "Great Tusk", type: 'fighting', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/55.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/55_hires.png' },
      { id: 56, name: "Sandy Shocks ex", type: 'fighting', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/56.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/56_hires.png' },
      { id: 57, name: "Okidogi", type: 'dark', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/57.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/57_hires.png' },
      { id: 58, name: "Cornerstone Mask Ogerpon ex", type: 'fighting', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/58.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/58_hires.png' },
      { id: 59, name: "Umbreon", type: 'dark', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/59.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/59_hires.png' },
      { id: 60, name: "Umbreon ex", type: 'dark', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/60.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/60_hires.png' },
      { id: 61, name: "Sneasel", type: 'dark', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/61.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/61_hires.png' },
      { id: 62, name: "Houndour", type: 'dark', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/62.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/62_hires.png' },
      { id: 63, name: "Houndoom", type: 'dark', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/63.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/63_hires.png' },
      { id: 64, name: "Tyranitar ex", type: 'dark', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/64.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/64_hires.png' },
      { id: 65, name: "Roaring Moon", type: 'dark', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/65.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/65_hires.png' },
      { id: 66, name: "Bronzor", type: 'steel', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/66.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/66_hires.png' },
      { id: 67, name: "Bronzong", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/67.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/67_hires.png' },
      { id: 68, name: "Heatran", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/68.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/68_hires.png' },
      { id: 69, name: "Duraludon", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/69.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/69_hires.png' },
      { id: 70, name: "Archaludon", type: 'steel', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/70.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/70_hires.png' },
      { id: 71, name: "Dreepy", type: 'dragon', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/71.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/71_hires.png' },
      { id: 72, name: "Drakloak", type: 'dragon', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/72.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/72_hires.png' },
      { id: 73, name: "Dragapult ex", type: 'dragon', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/73.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/73_hires.png' },
      { id: 74, name: "Eevee", type: 'normal', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/74.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/74_hires.png' },
      { id: 75, name: "Eevee ex", type: 'normal', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/75.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/75_hires.png' },
      { id: 76, name: "Snorlax ex", type: 'normal', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/76.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/76_hires.png' },
      { id: 77, name: "Hoothoot", type: 'normal', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/77.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/77_hires.png' },
      { id: 78, name: "Noctowl", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/78.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/78_hires.png' },
      { id: 79, name: "Dunsparce", type: 'normal', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/79.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/79_hires.png' },
      { id: 80, name: "Dudunsparce", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/80.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/80_hires.png' },
      { id: 81, name: "Miltank", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/81.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/81_hires.png' },
      { id: 82, name: "Lugia ex", type: 'normal', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/82.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/82_hires.png' },
      { id: 83, name: "Buneary", type: 'normal', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/83.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/83_hires.png' },
      { id: 84, name: "Lopunny", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/84.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/84_hires.png' },
      { id: 85, name: "Fan Rotom", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/85.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/85_hires.png' },
      { id: 86, name: "Regigigas", type: 'normal', rarity: 'R', imageSmall: 'https://images.pokemontcg.io/sv8pt5/86.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/86_hires.png' },
      { id: 87, name: "Shaymin", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/87.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/87_hires.png' },
      { id: 88, name: "Furfrou", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/88.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/88_hires.png' },
      { id: 89, name: "Hawlucha", type: 'normal', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/89.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/89_hires.png' },
      { id: 90, name: "Noibat", type: 'normal', rarity: 'C', imageSmall: 'https://images.pokemontcg.io/sv8pt5/90.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/90_hires.png' },
      { id: 91, name: "Noivern ex", type: 'normal', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/91.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/91_hires.png' },
      { id: 92, name: "Terapagos ex", type: 'normal', rarity: 'RR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/92.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/92_hires.png' },
      { id: 93, name: "Amarys", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/93.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/93_hires.png' },
      { id: 94, name: "Area Zero Underdepths", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/94.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/94_hires.png' },
      { id: 95, name: "Binding Mochi", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/95.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/95_hires.png' },
      { id: 96, name: "Black Belt's Training (Kanto)", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/96.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/96_hires.png' },
      { id: 97, name: "Black Belt's Training (Johto)", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/97.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/97_hires.png' },
      { id: 98, name: "Black Belt's Training (Sinnoh)", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/98.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/98_hires.png' },
      { id: 99, name: "Black Belt's Training (Kalos)", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/99.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/99_hires.png' },
      { id: 100, name: "Briar", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/100.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/100_hires.png' },
      { id: 101, name: "Buddy-Buddy Poffin", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/101.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/101_hires.png' },
      { id: 102, name: "Bug Catching Set", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/102.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/102_hires.png' },
      { id: 103, name: "Carmine", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/103.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/103_hires.png' },
      { id: 104, name: "Ciphermaniac's Codebreaking", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/104.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/104_hires.png' },
      { id: 105, name: "Crispin", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/105.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/105_hires.png' },
      { id: 106, name: "Earthen Vessel", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/106.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/106_hires.png' },
      { id: 107, name: "Explorer's Guidance", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/107.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/107_hires.png' },
      { id: 108, name: "Festival Grounds", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/108.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/108_hires.png' },
      { id: 109, name: "Friends in Paldea", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/109.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/109_hires.png' },
      { id: 110, name: "Glass Trumpet", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/110.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/110_hires.png' },
      { id: 111, name: "Haban Berry", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/111.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/111_hires.png' },
      { id: 112, name: "Janine's Secret Art", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/112.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/112_hires.png' },
      { id: 113, name: "Kieran", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/113.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/113_hires.png' },
      { id: 114, name: "Lacey", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/114.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/114_hires.png' },
      { id: 115, name: "Larry's Skill", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/115.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/115_hires.png' },
      { id: 116, name: "Max Rod", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/116.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/116_hires.png' },
      { id: 117, name: "Maximum Belt", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/117.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/117_hires.png' },
      { id: 118, name: "Ogre's Mask", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/118.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/118_hires.png' },
      { id: 119, name: "Prime Catcher", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/119.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/119_hires.png' },
      { id: 120, name: "Professor Sada's Vitality", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/120.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/120_hires.png' },
      { id: 121, name: "Professor Turo's Scenario", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/121.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/121_hires.png' },
      { id: 122, name: "Professor's Research (Oak)", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/122.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/122_hires.png' },
      { id: 123, name: "Professor's Research (Elm)", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/123.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/123_hires.png' },
      { id: 124, name: "Professor's Research (Rowan)", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/124.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/124_hires.png' },
      { id: 125, name: "Professor's Research (Sycamore)", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/125.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/125_hires.png' },
      { id: 126, name: "Rescue Board", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/126.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/126_hires.png' },
      { id: 127, name: "Roto Stick", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/127.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/127_hires.png' },
      { id: 128, name: "Scoop Up Cyclone", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/128.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/128_hires.png' },
      { id: 129, name: "Sparkling Crystal", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/129.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/129_hires.png' },
      { id: 130, name: "Techno Radar", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/130.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/130_hires.png' },
      { id: 131, name: "Treasure Tracker", type: 'trainer', rarity: 'U', imageSmall: 'https://images.pokemontcg.io/sv8pt5/131.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/131_hires.png' },
      { id: 132, name: "Amarys", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/132.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/132_hires.png' },
      { id: 133, name: "Atticus", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/133.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/133_hires.png' },
      { id: 134, name: "Brassius", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/134.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/134_hires.png' },
      { id: 135, name: "Eri", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/135.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/135_hires.png' },
      { id: 136, name: "Friends in Paldea", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/136.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/136_hires.png' },
      { id: 137, name: "Giacomo", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/137.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/137_hires.png' },
      { id: 138, name: "Larry's Skill", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/138.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/138_hires.png' },
      { id: 139, name: "Mela", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/139.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/139_hires.png' },
      { id: 140, name: "Ortega", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/140.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/140_hires.png' },
      { id: 141, name: "Raifort", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/141.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/141_hires.png' },
      { id: 142, name: "Ryme", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/142.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/142_hires.png' },
      { id: 143, name: "Penny", type: 'trainer', rarity: 'SR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/143.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/143_hires.png' },
      { id: 144, name: "Leafeon ex", type: 'grass', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/144.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/144_hires.png' },
      { id: 145, name: "Teal Mask Ogerpon ex", type: 'grass', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/145.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/145_hires.png' },
      { id: 146, name: "Flareon ex", type: 'fire', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/146.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/146_hires.png' },
      { id: 147, name: "Hearthflame Mask Ogerpon ex", type: 'fire', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/147.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/147_hires.png' },
      { id: 148, name: "Vaporeon ex", type: 'water', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/148.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/148_hires.png' },
      { id: 149, name: "Glaceon ex", type: 'water', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/149.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/149_hires.png' },
      { id: 150, name: "Wellspring Mask Ogerpon ex", type: 'water', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/150.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/150_hires.png' },
      { id: 151, name: "Jolteon ex", type: 'lightning', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/151.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/151_hires.png' },
      { id: 152, name: "Iron Hands ex", type: 'lightning', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/152.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/152_hires.png' },
      { id: 153, name: "Iron Thorns ex", type: 'lightning', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/153.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/153_hires.png' },
      { id: 154, name: "Espeon ex", type: 'psychic', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/154.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/154_hires.png' },
      { id: 155, name: "Sylveon ex", type: 'psychic', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/155.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/155_hires.png' },
      { id: 156, name: "Lucario ex", type: 'fighting', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/156.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/156_hires.png' },
      { id: 157, name: "Sandy Shocks ex", type: 'fighting', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/157.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/157_hires.png' },
      { id: 158, name: "Cornerstone Mask Ogerpon ex", type: 'fighting', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/158.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/158_hires.png' },
      { id: 159, name: "Umbreon ex", type: 'dark', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/159.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/159_hires.png' },
      { id: 160, name: "Tyranitar ex", type: 'dark', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/160.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/160_hires.png' },
      { id: 161, name: "Dragapult ex", type: 'dragon', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/161.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/161_hires.png' },
      { id: 162, name: "Eevee ex", type: 'normal', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/162.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/162_hires.png' },
      { id: 163, name: "Snorlax ex", type: 'normal', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/163.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/163_hires.png' },
      { id: 164, name: "Lugia ex", type: 'normal', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/164.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/164_hires.png' },
      { id: 165, name: "Noivern ex", type: 'normal', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/165.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/165_hires.png' },
      { id: 166, name: "Terapagos ex", type: 'normal', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/166.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/166_hires.png' },
      { id: 167, name: "Pikachu ex", type: 'lightning', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/167.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/167_hires.png' },
      { id: 168, name: "Bloodmoon Ursaluna", type: 'fighting', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/168.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/168_hires.png' },
      { id: 169, name: "Hydrapple ex", type: 'grass', rarity: 'SAR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/169.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/169_hires.png' },
      { id: 170, name: "Iron Leaves ex", type: 'grass', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/170.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/170_hires.png' },
      { id: 171, name: "Teal Mask Ogerpon ex", type: 'grass', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/171.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/171_hires.png' },
      { id: 172, name: "Walking Wake ex", type: 'water', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/172.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/172_hires.png' },
      { id: 173, name: "Pikachu ex", type: 'lightning', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/173.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/173_hires.png' },
      { id: 174, name: "Iron Valiant ex", type: 'psychic', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/174.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/174_hires.png' },
      { id: 175, name: "Iron Crown ex", type: 'steel', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/175.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/175_hires.png' },
      { id: 176, name: "Pecharunt ex", type: 'dark', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/176.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/176_hires.png' },
      { id: 177, name: "Gholdengo ex", type: 'steel', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/177.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/177_hires.png' },
      { id: 178, name: "Raging Bolt ex", type: 'dragon', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/178.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/178_hires.png' },
      { id: 179, name: "Eevee ex", type: 'normal', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/179.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/179_hires.png' },
      { id: 180, name: "Terapagos ex", type: 'normal', rarity: 'MUR', imageSmall: 'https://images.pokemontcg.io/sv8pt5/180.png', imageLarge: 'https://images.pokemontcg.io/sv8pt5/180_hires.png' },
    ]
  },
};

let CURRENT_SET_ID = 'sv8';
let CARD_SET = PACK_DATA[CURRENT_SET_ID].info;
let CARDS = PACK_DATA[CURRENT_SET_ID].cards;
let MAX_IMAGE_ID = CARD_SET.maxImageId;

function changeSet(setId) {
  if (PACK_DATA[setId]) {
    CURRENT_SET_ID = setId;
    CARD_SET = PACK_DATA[setId].info;
    CARDS = PACK_DATA[setId].cards;
    MAX_IMAGE_ID = CARD_SET.maxImageId;
    return true;
  }
  return false;
}

function getCardImageUrl(cardId, size, setId) {
  setId = setId || CURRENT_SET_ID;
  size = size || 400;
  var setCards = PACK_DATA[setId] && PACK_DATA[setId].cards;
  if (!setCards) return "/assets/cards/SD1/001.svg";
  var card = setCards.find(function(c) { return c.id === cardId; });
  if (card) {
    if (size >= 600 && card.imageLarge) return card.imageLarge;
    if (card.imageSmall) return card.imageSmall;
  }
  return "/assets/cards/SD1/" + String(cardId).padStart(3, "0") + ".svg";
}

const RARITY_INFO = {
  'C':   { label: 'C',   fullName: 'Common',            color: '#9e9e9e', bgColor: '#f5f5f5' },
  'U':   { label: 'U',   fullName: 'Uncommon',          color: '#4caf50', bgColor: '#e8f5e9' },
  'R':   { label: 'R',   fullName: 'Rare',              color: '#2196f3', bgColor: '#e3f2fd' },
  'RR':  { label: 'RR',  fullName: 'Double Rare',       color: '#ff9800', bgColor: '#fff3e0' },
  'AR':  { label: 'AR',  fullName: 'Art Rare',          color: '#e040fb', bgColor: '#fce4ec' },
  'SR':  { label: 'SR',  fullName: 'Super Rare',        color: '#ffd700', bgColor: '#fffde7' },
  'SAR': { label: 'SAR', fullName: 'Special Art Rare',  color: '#d500f9', bgColor: '#f3e5f5' },
  'MUR': { label: 'MUR', fullName: 'Hyper Rare',        color: '#ffd700', bgColor: 'linear-gradient(135deg, #ff6b35, #ffd700, #ff1744)' },
};

const GACHA_PROBABILITY_DATA = {
  packSize: 10,
  slots: {
    '1~3': { label: 'Slot 1~3', description: 'Basic cards', probabilities: { C: 100 } },
    '4~5': { label: 'Slot 4~5', description: 'Basic/Uncommon', probabilities: { C: 40, U: 60 } },
    '6~7': { label: 'Slot 6~7', description: 'Uncommon/Rare', probabilities: { U: 70, R: 30 } },
    '8':   { label: 'Slot 8',   description: 'Rare+', probabilities: { R: 70, RR: 25, AR: 5 } },
    '9':   { label: 'Slot 9',   description: 'Rare+ (higher)', probabilities: { R: 50, RR: 30, AR: 15, SR: 5 } },
    '10':  { label: 'Slot 10',  description: 'High Rare slot', probabilities: { RR: 85, AR: 10, SR: 3, SAR: 1.5, MUR: 0.5 } },
  },
  godPack: { chance: 0.5, description: 'God Pack (AR 1 + SR 5 + SAR 4)' }
};